{
  "swagger" : "2.0",
  "info" : {
    "description" : "API do sistema de Licenciamento de Ambulantes de Salvador",
    "version" : "1.1.0",
    "title" : "LAS API",
    "contact" : {
      "email" : "admin@las.com"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host" : "virtserver.swaggerhub.com",
  "basePath" : "/tiagolpadua/las-api/1.1.0",
  "schemes" : [ "https" ],
  "paths" : {
    "/usuario" : {
      "get" : {
        "summary" : "Lista os usuarios",
        "description" : "Lista os usuários do LAS-API\n",
        "operationId" : "listarUsuarios",
        "produces" : [ "application/json" ],
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "Resultado da listagem",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/Usuario"
              }
            }
          }
        }
      },
      "post" : {
        "summary" : "Inclui um usuário",
        "description" : "Inclui um usuário no LAS-API",
        "operationId" : "incluirUsuario",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "usuario",
          "description" : "Usuário a ser incluído",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/Usuario"
          }
        } ],
        "responses" : {
          "201" : {
            "description" : "Usuário incluído com sucesso"
          },
          "400" : {
            "description" : "Entrada inválida"
          }
        }
      }
    },
    "/usuario/{usuarioId}" : {
      "get" : {
        "summary" : "Busca um usuário pelo ID",
        "description" : "Busca um único usuário",
        "operationId" : "buscarUsuarioPorId",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "usuarioId",
          "in" : "path",
          "description" : "ID do usuário a ser retornado",
          "required" : true,
          "type" : "string",
          "format" : "uuid"
        } ],
        "responses" : {
          "200" : {
            "description" : "Operação bem sucedida",
            "schema" : {
              "$ref" : "#/definitions/Usuario"
            }
          },
          "400" : {
            "description" : "ID inválido fornecido"
          },
          "404" : {
            "description" : "Usuário não encontrado"
          }
        }
      },
      "put" : {
        "summary" : "Atualiza um usuário no LAS-API com os dados do formulário",
        "operationId" : "atualizarUsuario",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "usuarioId",
          "in" : "path",
          "description" : "ID do usuário a ser atualizado",
          "required" : true,
          "type" : "string",
          "format" : "uuid"
        }, {
          "in" : "body",
          "name" : "usuario",
          "description" : "Usuário a ser atualizado",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/Usuario"
          }
        } ],
        "responses" : {
          "405" : {
            "description" : "Entrada inválida"
          }
        }
      },
      "delete" : {
        "summary" : "Exclui um usuário",
        "operationId" : "excluirUsuario",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "usuarioId",
          "in" : "path",
          "description" : "Id do usuário a ser excluído",
          "required" : true,
          "type" : "string",
          "format" : "uuid"
        } ],
        "responses" : {
          "400" : {
            "description" : "Id inválido fornecido"
          },
          "404" : {
            "description" : "Usuário não encontrado"
          }
        }
      }
    }
  },
  "definitions" : {
    "Usuario" : {
      "type" : "object",
      "required" : [ "id", "nome", "urlFotoPerfil" ],
      "properties" : {
        "id" : {
          "type" : "string",
          "format" : "uuid",
          "example" : "d290f1ee-6c54-4b01-90e6-d701748f0851"
        },
        "nome" : {
          "type" : "string",
          "example" : "Paulo Silva"
        },
        "urlFotoPerfil" : {
          "type" : "string",
          "example" : "https://randomuser.me/api/portraits/men/91.jpg"
        }
      }
    }
  }
}