{
  "swagger" : "2.0",
  "info" : {
    "description" : "API do sistema de Licenciamento de Ambulantes de Salvador",
    "version" : "1.1.0",
    "title" : "LAS API",
    "contact" : {
      "email" : "admin@las.com"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host" : "virtserver.swaggerhub.com",
  "basePath" : "/tiagolpadua/las-api/1.1.0",
  "schemes" : [ "https" ],
  "paths" : {
    "/usuario" : {
      "get" : {
        "summary" : "Lista os usuarios",
        "description" : "Lista os usuários do LAS-API\n",
        "operationId" : "listarUsuarios",
        "produces" : [ "application/json" ],
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "Resultado da listagem",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/Usuario"
              }
            }
          },
          "400" : {
            "description" : "bad input parameter"
          }
        }
      },
      "post" : {
        "summary" : "Inclui um usuário",
        "description" : "Inclui um usuário no sistema",
        "operationId" : "adicionarUsuario",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "usuario",
          "description" : "Usuário a ser adicionado",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/Usuario"
          }
        } ],
        "responses" : {
          "201" : {
            "description" : "Usuário criado"
          },
          "400" : {
            "description" : "Entrada inválida"
          }
        }
      }
    }
  },
  "definitions" : {
    "Usuario" : {
      "type" : "object",
      "required" : [ "id", "nome", "urlFotoPerfil" ],
      "properties" : {
        "id" : {
          "type" : "string",
          "format" : "uuid",
          "example" : "d290f1ee-6c54-4b01-90e6-d701748f0851"
        },
        "nome" : {
          "type" : "string",
          "example" : "Paulo Silva"
        },
        "urlFotoPerfil" : {
          "type" : "string",
          "example" : "https://randomuser.me/api/portraits/men/91.jpg"
        }
      }
    }
  }
}